# Generated by Django 2.2 on 2019-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_messageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='headpic',
            field=models.ImageField(blank=True, null=True, upload_to='media/userpic'),
        ),
    ]
